llm:
  max_tokens: 4096
  batch_size: 64
  max_concurrent: 32

paths:
  server_cache: cache/server
  mod_cache: cache/mod
  gkm_diff: cache/gkm-diff
  output: output

github:
  owner: chinosk6
  repo: GakumasTranslationData

character_names:
  amao: 有村麻央
  hski: 花海咲季
  hume: 花海佑芽
  fktn: 藤田琴音
  kllj: 葛城莉莉娅
  hrnm: 姫崎莉波
  shro: 広
  ssmk: 紫雲清夏
  ttmr: 月村手毬
  kcna: 倉本千奈
  hmsz: 秦谷美鈴
  atbm: 雨夜燕
  jsna: 十王星南
  cmmn: ""
  "{user}": "{user}"

octo:
  app_id: 400
  client_secret: 0jv0wsohnnsigttbfigushbtl3a8m7l5
  version: "705100"
  url: https://api.asset.game-gakuen-idolmaster.jp/
  api_key_seed: x5HFaJCJywDyuButLM0f
  cache_key: 9d8dfd7b1371612846f7ba44e01af160
  cache_iv: 1c6e6f9255c0e5412712f4010225e378
  data_path: cache/octo
